import React, { useState } from 'react';
import { adminAdjustCredits, findPlayers, getTransactions, getWallet } from '../services/creditService';

export default function CreditAdmin({ back, notify }) {
  const [playerId, setPlayerId] = useState(''); const [query, setQuery] = useState(''); const [matches, setMatches] = useState([]); const [wallet, setWallet] = useState(null); const [history, setHistory] = useState([]); const [amount, setAmount] = useState(''); const [reason, setReason] = useState('');
  const load = async (id = playerId) => { if (!id.trim()) return; setPlayerId(id.trim()); setWallet(await getWallet(id.trim())); setHistory(await getTransactions(id.trim())); };
  const search = async () => { if (!query.trim()) return; try { setMatches(await findPlayers(query.trim())); } catch (error) { notify(error.message); } };
  const adjust = async (direction) => { const value = Math.abs(Number(amount)); if (!value || !reason.trim()) return notify('Ingresá cantidad y motivo.'); if (!window.confirm(`${direction > 0 ? 'Agregar' : 'Quitar'} ${value} créditos a ${playerId}?`)) return; try { await adminAdjustCredits(playerId.trim(), direction * value, reason.trim()); await load(); setAmount(''); setReason(''); notify('Movimiento registrado.'); } catch (error) { notify(error.message); } };
  return <section className="admin page"><button className="back" onClick={back}>← VOLVER A ADMIN</button><div className="admin-heading"><div><p className="eyebrow">ADMINISTRACIÓN ECONÓMICA</p><h1>CRÉDITOS<br /><em>LXM</em></h1></div><p>Las operaciones de producción pasan por una RPC segura: el navegador no calcula ni modifica saldos.</p></div><section className="credit-admin"><div className="credit-panel"><label>Buscar usuario<input value={query} placeholder="@musta o nombre de usuario" onChange={(e) => setQuery(e.target.value)} /></label><button className="secondary" onClick={search}>BUSCAR USUARIO</button>{matches.map((item) => <button className="player-match" key={item.player_id} onClick={() => load(item.player_id)}>@{item.username} <small>◉ {item.balance_credits}</small></button>)}{wallet && <><h2>Saldo actual <b>◉ {wallet.balance}</b></h2><small>Usuario seleccionado: {playerId}</small><label>Cantidad<input type="number" min="1" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label>Motivo<input value={reason} placeholder="Prueba, compensación..." onChange={(e) => setReason(e.target.value)} /></label><div className="credit-actions"><button onClick={() => adjust(1)}>+ AGREGAR</button><button onClick={() => adjust(-1)}>− QUITAR</button></div></>}</div><div className="credit-history"><h2>HISTORIAL</h2>{history.map((item) => <article key={item.id}><b className={item.amount > 0 ? 'positive' : 'negative'}>{item.amount > 0 ? '+' : ''}{item.amount}</b><div><strong>{item.reason}</strong><small>{item.type} · {new Date(item.created_at).toLocaleString()}</small></div></article>)}{wallet && !history.length && <p className="empty">No hay movimientos para este usuario.</p>}</div></section></section>;
}
