import React from 'react';

const Card = ({ label, item, onChange, selector }) => <div className="loadout-card"><small>{label}</small><div className="loadout-visual">{item.image ? <img src={item.image} alt={item.name} /> : item.icon}</div><b>{item.name}</b><span>{item.skills?.join(' · ') || item.traits?.join(' · ') || 'Hilo activo'}</span><button onClick={() => document.getElementById(selector).scrollIntoView({ behavior: 'smooth' })}>CAMBIAR</button></div>;

export default function Lobby({ progress, catalog, bike, avatar, copilot, lobbyImage, back, start, equip }) {
  const avatarList = catalog.avatars.filter((item) => progress.avatars.includes(item.id));
  const bikeList = catalog.bikes.filter((item) => progress.bikes.includes(item.id));
  const show = (item) => item.image ? <img src={item.image} alt="" /> : <span>{item.icon}</span>;
  return <section className="lobby page"><button className="back" onClick={back}>← VOLVER AL HOME</button><div className="lobby-heading"><div><p className="eyebrow">PREPARACIÓN DE PARTIDA</p><h1>EL <em>LOBBY</em></h1></div><p>Equipá moto, piloto y copiloto. Cada rol aporta 3 decisiones: el juego sortea una de cada rol y te entrega esas 3 alternativas.</p></div><div className="workshop workshop-three" style={lobbyImage ? { backgroundImage: `linear-gradient(90deg,rgba(7,8,10,.96),rgba(7,8,10,.32)), url(${lobbyImage})` } : {}}><Card label="MOTO EQUIPADA" item={bike} selector="bike-selector" /><Card label="PILOTO EQUIPADO" item={avatar} selector="pilot-selector" /><Card label="COPILOTO EQUIPADO" item={copilot} selector="copilot-selector" /><div className="workshop-center"><span>◈</span><p>TALLER LXM</p><h2>LISTO PARA<br />LA <em>RUTA</em></h2><button className="play-button" onClick={start}>▶ EMPEZAR PARTIDA</button></div></div><section className="lobby-selectors lobby-three-selectors"><div id="bike-selector"><p className="eyebrow">GARAJE</p><h2>MOTOS</h2>{bikeList.map((item) => <button className={progress.equipped.bike === item.id ? 'selected' : ''} onClick={() => equip('bike', item.id)} key={item.id}>{show(item)}<span><b>{item.name}</b><small>Hilo de moto</small></span></button>)}</div><div id="pilot-selector"><p className="eyebrow">ROL 02</p><h2>PILOTO</h2>{avatarList.filter((item) => item.id !== progress.equipped.copilot).map((item) => <button className={progress.equipped.avatar === item.id ? 'selected' : ''} onClick={() => equip('avatar', item.id)} key={item.id}>{show(item)}<span><b>{item.name}</b><small>Hilo de piloto</small></span></button>)}</div><div id="copilot-selector"><p className="eyebrow">ROL 03</p><h2>COPILOTO</h2>{avatarList.filter((item) => item.id !== progress.equipped.avatar).map((item) => <button className={progress.equipped.copilot === item.id ? 'selected' : ''} onClick={() => equip('copilot', item.id)} key={item.id}>{show(item)}<span><b>{item.name}</b><small>Hilo de copiloto</small></span></button>)}</div></section></section>;
}
