import React, { useMemo, useState } from 'react';
import { saveCustomContent } from '../services/gameService';

const emptyOption = () => ({ text: '', result: '', followups: ['', '', ''] });
const fresh = () => ({ title: '', ownerType: 'cards', ownerId: '', options: [emptyOption(), emptyOption(), emptyOption()] });

export default function ThreadAdmin({ customContent, setCustomContent, catalog, back, notify }) {
  const [form, setForm] = useState(fresh);
  const [editing, setEditing] = useState(null);
  const owners = useMemo(() => catalog[form.ownerType] || [], [catalog, form.ownerType]);
  const updateOption = (index, key, value) => setForm({ ...form, options: form.options.map((option, i) => i === index ? { ...option, [key]: value } : option) });
  const updateFollowup = (index, followupIndex, value) => setForm({ ...form, options: form.options.map((option, i) => i === index ? { ...option, followups: option.followups.map((followup, j) => j === followupIndex ? value : followup) } : option) });
  const save = (event) => { event.preventDefault(); if (!form.title.trim() || !form.ownerId || form.options.some((option) => !option.text.trim() || option.followups.some((followup) => !followup.trim()))) { notify('Completá el título, objeto asignado, 3 opciones y sus 3 continuaciones.'); return; } const item = { ...form, id: editing || `thread-${Date.now()}` }; const next = { ...customContent, threads: editing ? customContent.threads.map((thread) => thread.id === editing ? item : thread) : [...customContent.threads, item] }; if (!saveCustomContent(next)) { notify('No se pudo guardar el hilo: liberá espacio local.'); return; } setCustomContent(next); setForm(fresh()); setEditing(null); notify(editing ? 'Hilo actualizado' : 'Hilo creado'); };
  const edit = (thread) => { setForm(thread); setEditing(thread.id); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const remove = (id) => { if (!window.confirm('¿Eliminar este hilo?')) return; const next = { ...customContent, threads: customContent.threads.filter((thread) => thread.id !== id) }; setCustomContent(next); saveCustomContent(next); notify('Hilo eliminado'); };
  return <section className="admin page"><button className="back" onClick={back}>← VOLVER A CONTENIDO</button><div className="admin-heading"><div><p className="eyebrow">PANEL ADMIN · HILOS</p><h1>EDITOR DE<br /><em>HILOS</em></h1></div><p>Un hilo se activa al equipar la carta, moto o avatar asignado. Sus opciones entran al sorteo del Lobby.</p></div><div className="thread-menu"><a href="/admin">CONTENIDO</a><strong>HILOS</strong></div><form className="thread-form" onSubmit={save}><div className="thread-basics"><label>Título del hilo<input value={form.title} placeholder="Ej. La carrera de Lucio" onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Se activa con<select value={form.ownerType} onChange={(e) => setForm({ ...form, ownerType: e.target.value, ownerId: '' })}><option value="cards">Carta</option><option value="bikes">Moto</option><option value="avatars">Avatar</option></select></label><label>Objeto asignado<select value={form.ownerId} onChange={(e) => setForm({ ...form, ownerId: e.target.value })}><option value="">Seleccionar…</option>{owners.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><h2>PRIMERA DECISIÓN: 3 OPCIONES</h2><div className="thread-options">{form.options.map((option, index) => <article key={index}><b>OPCIÓN {index + 1}</b><label>Decisión<input value={option.text} placeholder="Ej. Desafiar a Lucio" onChange={(e) => updateOption(index, 'text', e.target.value)} /></label><label>Resultado de elegirla<textarea value={option.result} placeholder="Qué sucede al elegirla" onChange={(e) => updateOption(index, 'result', e.target.value)} /></label><small>3 opciones para continuar después del resultado</small>{option.followups.map((followup, followupIndex) => <input key={followupIndex} value={followup} placeholder={`Continuación ${followupIndex + 1}`} onChange={(e) => updateFollowup(index, followupIndex, e.target.value)} />)}</article>)}</div><button className="play-button" type="submit">{editing ? 'GUARDAR HILO' : '+ CREAR HILO'}</button>{editing && <button className="cancel-edit" type="button" onClick={() => { setForm(fresh()); setEditing(null); }}>CANCELAR</button>}</form><section className="thread-list"><h2>HILOS CREADOS</h2>{customContent.threads.map((thread) => <article key={thread.id}><div><b>{thread.title}</b><small>{thread.ownerType} · {thread.ownerId}</small><p>{thread.options.map((option) => option.text).join(' · ')}</p></div><button onClick={() => edit(thread)}>EDITAR</button><button onClick={() => remove(thread.id)}>ELIMINAR</button></article>)}{!customContent.threads.length && <p className="empty">Todavía no hay hilos. Creá uno y asignalo a una carta, moto o avatar.</p>}</section></section>;
}
